import { Geist, Yellowtail, Parkinsans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const yellowtail = Yellowtail({
  variable: "--font-yellowtail", // Changed variable name for clarity
  weight: "400", // Specify the weight here
  subsets: ["latin"],
});

const parkinsasn = Parkinsans({
  variable: "--font-parkinsans", // Changed variable name for clarity
  weight: "400", // Specify the weight here
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${yellowtail.variable} ${parkinsasn.variable} transition ease-in-out antialiased`}
      >
        {children}
      </body>
    </html>
  );
}