import { Geist, Yellowtail, Parkinsans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Hair Donation 555",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} transition ease-in-out antialiased`}
      >
        {children}
      </body>
    </html>
  );
}